package base

import "time"

const (
	VAR_EXECUTABLE_NAME        = "EXECUTABLE"
	VAR_EXECUTABLE_FOLDER_NAME = "EXECUTABLE_FOLDER"
	VAR_USER_FOLDER_NAME       = "USER_FOLDER"
	VAR_MACHINE_FOLDER_NAME    = "MACHINE_FOLDER"
	VAR_CURRENT_FOLDER_NAME    = "CURRENT_FOLDER"
	VAR_TEMP_FOLDER_NAME       = "TEMP_FOLDER"
	VAR_APP_PACKAGE_NAME       = "APP_PACKAGE"
	VAR_APP_NAME               = "APP_NAME"
	VAR_APP_ROOT_FOLDER_NAME   = "APP_ROOT_FOLDER"
	VAR_APP_STORE_FOLDER_NAME  = "APP_STORE_FOLDER"
	VAR_APP_CONFIG_FOLDER_NAME = "APP_CONFIG_FOLDER"
)

var (
	NilString string
	NilTime   time.Time
)
